#!/usr/bin/env python
# encoding: utf-8

import argparse
from collections import Counter
import os
import sys


def main(path_to_logfile):
    """Print top ten most frequently logged IP addresses from specified log.

    Args:
        path_to_logfile (str): Path to NGINX log file to parse.

    Returns:
        int: Success status.
    """
    counter = Counter({})

    with open(path_to_logfile, 'r') as file_:
        for line in file_:
            ip_addr = line.split(None, 1)[0]
            counter[ip_addr] = counter.get(ip_addr, 0) + 1

    print '\n'.join(
        ['{1} {0}'.format(ip, count) for ip, count in counter.most_common(10)])

    return 0


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Print top ten most frequently logged IP addresses.",
        add_help=True)
    parser.add_argument(
        'path_to_logfile', metavar='PATH', help='path to NGINX log file')
    args = parser.parse_args()

    if not os.path.exists(args.path_to_logfile):
        print "No such log file"
        sys.exit(1)

    sys.exit(main(args.path_to_logfile))
